
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost
 

development:
  <<: *default
  database: scutisu_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  <<: *default
  database: scutisu_test

production:
  <<: *default
  database: scutisu_production
  password: <%= ENV['SCUTISU_DATABASE_PASSWORD'] %>
